name: Build Images

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 22 * * *'

jobs:
  keycloak:
    name: Build keycloak Images

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Docker Login
        env:
          DOCKER_USERNAME: $
          DOCKER_PASSWORD: $
        run: |-
          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      - name: Run Crossbuild
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -t "homelabs/keycloak:latest" \
            -t "homelabs/keycloak:$(date '+%Y%m%d%H%M')" --push .
